[versions]
agp = "8.13.2"
kotlin = "2.3.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
mapsMobile = "4.29.0-lite"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
maps-mobile = { module = "com.yandex.android:maps.mobile", version.ref = "mapsMobile" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }