[versions]
agp = "8.13.1"
kotlin = "2.2.21"
googleServices = "4.4.4"
coreKtx = "1.17.0"
appcompat = "1.7.1"
mapsKtx = "5.2.2"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
playServicesLocation = "21.3.0"
playServicesMaps = "19.2.0"
playServices = "18.9.0"
desugaring = "2.1.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
maps-ktx = { module = "com.google.maps.android:maps-ktx", version.ref = "mapsKtx" }
maps-utils-ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "mapsKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services = { group = "com.google.android.gms", name = "play-services-base", version.ref = "playServices" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }